# Site settings
name: Pratik Kumar
title: Pratik Kumar | Data Scientist
description: A data science and deep learning enthusiast focused on building data driven products A.I. research.
url: https://pr2tik1.github.io/
baseurl: 'https://pr2tik1.github.io/'
email: pr2tik1@gmail.com
cover: https://pr2tik1.github.io/img/og.png
logo: https://pr2tik1.github.io/img/emojis/rocket.png
resume: https://pr2tik1.github.io/resume.pdf
social:
  - title: email
    url: mailto:pr2tik1@gmail.com
  - title: twitter
    url: https://twitter.com/PratikPkb
  - title: instagram
    url: https://instagram.com/pratikkumar04
  - title: github
    url: https://github.com/pr2tik1
  - title: linkedin
    url: https://www.linkedin.com/in/pratik-kumar04

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
